version: "3"

services:

  admin-api:
    image: suba2502/admin-api
    ports:
      - "5001:5001"
    depends_on:
      - db

  user-api:
    image: suba2502/user-api
    ports:
      - "5002:5002"
    depends_on:
      - db

  admin-ui:
    image: suba2502/admin-ui
    ports:
      - "3001:3001"

  user-ui:
    image: suba2502/user-ui
    ports:
      - "3000:3000"

  db:
    image: mongo
    ports:
      - "27017:27017"
